FROM node:16

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Create wallet directory
RUN mkdir -p wallet

# Expose API port
EXPOSE 3002

# Command to run the API server
CMD ["node", "src/blockchain/server-docker.cjs"] 